name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 12 * * 1' # 12pm Monday
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        toolchain: [nightly, stable]
        flags: ['', --all-features]
        exclude:
        - toolchain: stable
          flags: --all-features

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        components: clippy
    - run: cargo clippy ${{ matrix.flags }}
    - run: cargo build ${{ matrix.flags }}
    - run: cargo test ${{ matrix.flags }}

  rustfmt-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo fmt -- --check
